name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: checkout rose.parser
      uses: actions/checkout@v3
      with:
        repository: RicoP/rose.parser
        path: ./rose.parser
    
    - name: checkout roselib
      uses: actions/checkout@v3
      with:
        repository: RicoP/roselib
        path: ./roselib

    - name: checkout premake-comppp
      uses: actions/checkout@v3
      with:
        repository: RicoP/premake-comppp
        path: ./premake-comppp
    
    - name: Setup premake
      uses: abel0b/setup-premake@v2.1
      with:
        version: "5.0.0-beta2"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: create solution
      working-directory: rose.parser
      run: premake5 vs2019

    - name: Build solution
      working-directory: rose.parser
      run: ./solution_compile.bat

    - name: execute test
      working-directory: rose.parser/test
      run: .\..\.build\bin\DebugTest\rose.parser.exe --include enginesettings.h test_header.h -O serializer.h -J test_json.json -V

    - name: show serializer.h
      working-directory: rose.parser
      run: TYPE test/serializer.h

    - name: show test_json.json
      working-directory: rose.parser
      run: TYPE test/test_json.json
